# Generated by Django 4.1.7 on 2023-04-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=30, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('author', models.CharField(max_length=60)),
                ('file', models.FileField(blank=True, upload_to='books/')),
                ('year', models.SmallIntegerField()),
                ('slug', models.SlugField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('added', models.DateField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('genre', models.ManyToManyField(blank=True, related_name='genres', to='books.genre')),
            ],
        ),
    ]
