# Generated by Django 4.1.7 on 2023-04-03 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='is_liked',
            new_name='in_favorites',
        ),
    ]
